.TH MYCOMMAND 1 "22 abril 2024" "Version 1.0" "simple shell"

.SH NAME
simple shell - A brief description of what mycommand does.

.SH SYNOPSIS
.B mycommand
[\fIOPTIONS\fR]
[\fIARGUMENTS\fR]

.SH DESCRIPTION
is a shell command that execute a command from the standart input or from file

.SH OPTIONS
.TP
\fB-a, --option-a\fR
Description of option a.

.TP
\fB-b, --option-b\fR
Description of option b.

.SH EXAMPLES
\fBmycommand -a arg1 -b arg2\fR
An example illustrating how to use mycommand with options.

.SH SEE ALSO
List of related commands or resources.

.SH AUTHORS
Kevin rentas

gadiel Rivera

.SH FILES

.SH AVAILABILITY
Where to find the latest version.

.SH ACKNOWLEDGEMENTS
Acknowledgements or credits.

.SH COMMAND-LINE OPTIONS
More detailed explanation of command-line options.

.SH ENVIRONMENT VARIABLES


.SH HISTORY
version 1.0


